# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 750)
        MainWindow.setStyleSheet("background-color: rgb(131, 255, 93);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.result = QtWidgets.QLabel(self.centralwidget)
        self.result.setGeometry(QtCore.QRect(0, 0, 500, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.result.setFont(font)
        self.result.setStyleSheet("background-color: rgb(34, 255, 104);")
        self.result.setObjectName("result")
        self.b0 = QtWidgets.QPushButton(self.centralwidget)
        self.b0.setGeometry(QtCore.QRect(0, 630, 211, 121))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.b0.setFont(font)
        self.b0.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.b0.setObjectName("b0")
        self.rovno = QtWidgets.QPushButton(self.centralwidget)
        self.rovno.setGeometry(QtCore.QRect(290, 630, 211, 121))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.rovno.setFont(font)
        self.rovno.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.rovno.setObjectName("rovno")
        self.b7 = QtWidgets.QPushButton(self.centralwidget)
        self.b7.setGeometry(QtCore.QRect(0, 70, 141, 121))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.b7.setFont(font)
        self.b7.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.b7.setObjectName("b7")
        self.b9 = QtWidgets.QPushButton(self.centralwidget)
        self.b9.setGeometry(QtCore.QRect(360, 70, 141, 121))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.b9.setFont(font)
        self.b9.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.b9.setObjectName("b9")
        self.b8 = QtWidgets.QPushButton(self.centralwidget)
        self.b8.setGeometry(QtCore.QRect(180, 70, 141, 121))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.b8.setFont(font)
        self.b8.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.b8.setObjectName("b8")
        self.b6 = QtWidgets.QPushButton(self.centralwidget)
        self.b6.setGeometry(QtCore.QRect(360, 250, 141, 121))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.b6.setFont(font)
        self.b6.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.b6.setObjectName("b6")
        self.b5 = QtWidgets.QPushButton(self.centralwidget)
        self.b5.setGeometry(QtCore.QRect(180, 250, 141, 121))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.b5.setFont(font)
        self.b5.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.b5.setObjectName("b5")
        self.b4 = QtWidgets.QPushButton(self.centralwidget)
        self.b4.setGeometry(QtCore.QRect(0, 250, 141, 121))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.b4.setFont(font)
        self.b4.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.b4.setObjectName("b4")
        self.b3 = QtWidgets.QPushButton(self.centralwidget)
        self.b3.setGeometry(QtCore.QRect(360, 430, 141, 121))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.b3.setFont(font)
        self.b3.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.b3.setObjectName("b3")
        self.b2 = QtWidgets.QPushButton(self.centralwidget)
        self.b2.setGeometry(QtCore.QRect(180, 430, 141, 121))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.b2.setFont(font)
        self.b2.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.b2.setObjectName("b2")
        self.b1 = QtWidgets.QPushButton(self.centralwidget)
        self.b1.setGeometry(QtCore.QRect(0, 430, 141, 121))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.b1.setFont(font)
        self.b1.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.b1.setObjectName("b1")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Culculate"))
        self.result.setText(_translate("MainWindow", "0"))
        self.b0.setText(_translate("MainWindow", "0"))
        self.rovno.setText(_translate("MainWindow", "="))
        self.b7.setText(_translate("MainWindow", "7"))
        self.b9.setText(_translate("MainWindow", "9"))
        self.b8.setText(_translate("MainWindow", "8"))
        self.b6.setText(_translate("MainWindow", "6"))
        self.b5.setText(_translate("MainWindow", "5"))
        self.b4.setText(_translate("MainWindow", "4"))
        self.b3.setText(_translate("MainWindow", "3"))
        self.b2.setText(_translate("MainWindow", "2"))
        self.b1.setText(_translate("MainWindow", "1"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
